import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'location.freezed.dart';
part 'location.g.dart';

@freezed
class Location with _$Location {
  factory Location({
    required String id,
    required String name,
    String? disassembledName,
    required List<double> coord,
    required String type,
    required int matchQuality,
    List<int>? productClasses,
    required bool isBest,
  }) = _Location;
  factory Location.fromJson(Map<String, dynamic> json) =>
      _$LocationFromJson(json);
}

extension ExtLocation on Location {
  String? get ortsName => disassembledName?.split(",").length == 2
      ? disassembledName?.split(",").last.trimLeft()
      : "-";
  List<String> buildContent() {
    final list = [
      "type: $type",
      "Match Quality: $matchQuality",
      "Ortsname: $ortsName",
      productClasses != null ? "classes: ${productClasses!.join(",")}" : '',
    ]..removeWhere((value) {
        return value.isEmpty;
      });
    return list;
  }
}
